name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

    # third party
  go_router: ^14.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  rxdart: ^0.27.7
  bloc_concurrency: ^0.2.2
  infinite_scroll_pagination: ^4.0.0
  http: ^1.2.1
  intl: ^0.19.0
  dio: ^5.4.3+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/